import { RecoveryCase } from '../agent/types';
import { clearAndSeedCases, addAuditLog } from './index';

export const INITIAL_SYNTHETIC_CASES: RecoveryCase[] = [
  {
    id: 'case_101',
    customer_name: 'Aarav Sharma',
    customer_email: 'aarav.sharma@techcorp.in',
    customer_phone: '+91 98765 43210',
    amount: 14999.00,
    currency: 'INR',
    channel: 'checkout',
    issue_type: 'BANK_DOWNTIME',
    failure_code: 'BAD_REQUEST_GATEWAY_TIMEOUT',
    failure_message: 'HDFC Bank core banking system timed out during 3DS verification.',
    bank_name: 'HDFC Bank',
    payment_method: 'NetBanking',
    status: 'at_risk',
    risk_score: 0.25,
    attempts_count: 1,
    max_retries: 3,
    recovered_amount: 0,
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    recommended_action: 'AUTO_RETRY',
    diagnosis_summary: 'Temporary gateway timeout detected at HDFC Bank. Bank health metrics indicate 94% recovery within 15 mins.',
  },
  {
    id: 'case_102',
    customer_name: 'Priya Patel',
    customer_email: 'priya.patel@designstudio.co',
    customer_phone: '+91 98234 56789',
    amount: 3499.00,
    currency: 'INR',
    channel: 'subscription',
    issue_type: 'INSUFFICIENT_FUNDS',
    failure_code: 'PAYMENT_CARD_DECLINED_INSUFFICIENT_FUNDS',
    failure_message: 'Issuer bank declined recurring debit due to insufficient account balance.',
    bank_name: 'Axis Bank',
    payment_method: 'Visa Debit Card ending 4821',
    status: 'at_risk',
    risk_score: 0.40,
    attempts_count: 1,
    max_retries: 3,
    recovered_amount: 0,
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    recommended_action: 'SEND_SMART_PAYMENT_LINK',
    diagnosis_summary: 'Soft decline for monthly subscription payment. Recommended smart link with UPI/card options sent via SMS & WhatsApp.',
  },
  {
    id: 'case_103',
    customer_name: 'Vikram Mehta',
    customer_email: 'v.mehta@logistics.com',
    customer_phone: '+91 97112 34567',
    amount: 48500.00,
    currency: 'INR',
    channel: 'invoice',
    issue_type: 'EXPIRED_CARD',
    failure_code: 'PAYMENT_CARD_EXPIRED',
    failure_message: 'Saved Mastercard ending 9012 has expired (Expiry: 07/26).',
    bank_name: 'ICICI Bank',
    payment_method: 'Mastercard Credit Card',
    status: 'at_risk',
    risk_score: 0.65,
    attempts_count: 1,
    max_retries: 3,
    recovered_amount: 0,
    created_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    recommended_action: 'PROMPT_CARD_UPDATE',
    diagnosis_summary: 'Hard decline due to expired payment instrument. Automated card update portal link generated.',
  },
  {
    id: 'case_104',
    customer_name: 'Sneha Roy',
    customer_email: 'sneha.roy@gmail.com',
    customer_phone: '+91 99001 12233',
    amount: 8990.00,
    currency: 'INR',
    channel: 'checkout',
    issue_type: 'ABANDONED_CHECKOUT',
    failure_code: 'CHECKOUT_WINDOW_CLOSED',
    failure_message: 'Customer initiated checkout popup but closed modal before entering 3DS OTP.',
    bank_name: 'SBI Bank',
    payment_method: 'UPI (Google Pay)',
    status: 'at_risk',
    risk_score: 0.30,
    attempts_count: 0,
    max_retries: 3,
    recovered_amount: 0,
    created_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    recommended_action: 'SEND_SMART_PAYMENT_LINK',
    diagnosis_summary: 'High recovery potential (85%). Instant 1-click payment link generated for quick checkout resumption.',
  },
  {
    id: 'case_105',
    customer_name: 'Rohan Gupta',
    customer_email: 'rohan.g@fintechconsult.io',
    customer_phone: '+91 96543 21098',
    amount: 125000.00,
    currency: 'INR',
    channel: 'recurring',
    issue_type: 'REPEATED_FAILURE',
    failure_code: 'GATEWAY_ERROR_MAX_ATTEMPTS_EXCEEDED',
    failure_message: '3 consecutive failures recorded across 2 different payment methods.',
    bank_name: 'Kotak Bank',
    payment_method: 'Corporate Card / NetBanking',
    status: 'at_risk',
    risk_score: 0.85,
    attempts_count: 3,
    max_retries: 3,
    recovered_amount: 0,
    created_at: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    recommended_action: 'ESCALATE_HUMAN_OPS',
    diagnosis_summary: 'High-value high-risk case. Maximum automated attempts reached. Escalate to Razorpay Merchant Account Manager.',
  },
  {
    id: 'case_106',
    customer_name: 'Ananya Iyer',
    customer_email: 'ananya.iyer@cloudscale.net',
    customer_phone: '+91 95432 10987',
    amount: 2199.00,
    currency: 'INR',
    channel: 'subscription',
    issue_type: 'CARD_DECLINED',
    failure_code: 'PAYMENT_DECLINED_BY_ISSUER',
    failure_message: 'Generic card decline by issuer bank.',
    bank_name: 'Axis Bank',
    payment_method: 'Visa Credit Card ending 1123',
    status: 'at_risk',
    risk_score: 0.35,
    attempts_count: 1,
    max_retries: 3,
    recovered_amount: 0,
    created_at: new Date(Date.now() - 1000 * 60 * 80).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 80).toISOString(),
    recommended_action: 'SWITCH_GATEWAY_RETRY',
    diagnosis_summary: 'Secondary gateway route (Razorpay PayU Fallback) available with 91% success rate.',
  },
  {
    id: 'case_107',
    customer_name: 'Kabir Verma',
    customer_email: 'kabir.verma@retailx.in',
    customer_phone: '+91 94321 09876',
    amount: 75000.00,
    currency: 'INR',
    channel: 'invoice',
    issue_type: 'FRAUD_RISK',
    failure_code: 'RISK_ENGINE_HIGH_VELOCITY_BLOCK',
    failure_message: 'Razorpay Fraud Shield flagged unusual IP address geolocation mismatch.',
    bank_name: 'HDFC Bank',
    payment_method: 'International Credit Card',
    status: 'at_risk',
    risk_score: 0.95,
    attempts_count: 1,
    max_retries: 3,
    recovered_amount: 0,
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    recommended_action: 'ESCALATE_HUMAN_OPS',
    diagnosis_summary: 'CRITICAL: High fraud risk score (0.95). Automated retries disabled to protect merchant from chargebacks.',
  },
  {
    id: 'case_108',
    customer_name: 'Neha Kapoor',
    customer_email: 'neha.k@fashionhub.com',
    customer_phone: '+91 93210 98765',
    amount: 5400.00,
    currency: 'INR',
    channel: 'checkout',
    issue_type: 'BANK_DOWNTIME',
    failure_code: 'BANK_MAINTENANCE_DOWNTIME',
    failure_message: 'SBI NetBanking scheduled maintenance window (01:00 AM - 03:00 AM).',
    bank_name: 'SBI Bank',
    payment_method: 'NetBanking',
    status: 'at_risk',
    risk_score: 0.20,
    attempts_count: 1,
    max_retries: 3,
    recovered_amount: 0,
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    recommended_action: 'AUTO_RETRY',
    diagnosis_summary: 'Maintenance window active. Intelligent delay retry scheduled post 03:00 AM.',
  }
];

export function seedDatabase() {
  clearAndSeedCases(INITIAL_SYNTHETIC_CASES);

  // Add initial audit logs for each case
  for (const c of INITIAL_SYNTHETIC_CASES) {
    addAuditLog({
      case_id: c.id,
      timestamp: c.created_at,
      actor: 'SYSTEM',
      step_name: 'DIAGNOSE',
      action_taken: 'Payment Risk Detected',
      reasoning: `Transaction failed with code ${c.failure_code}. System flagged as at-risk revenue (${c.issue_type}).`,
      input_data: JSON.stringify({ amount: c.amount, failure_code: c.failure_code, bank: c.bank_name }),
      output_data: JSON.stringify({ risk_score: c.risk_score, initial_status: c.status }),
      status: 'LOGGED',
    });
  }
}

